spring:
  datasource:
    url: jdbc:oracle:${DB_DESENV_URL:thin:@oracle.fiap.com.br}:${DB_PROD_PORT:1521}:${DB_DESENV_NAME:ORCL}
    username: ${DB_DESENV_USERNAME:RM551289}
    password: ${DB_DESENV_PASSWORD:010502}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true